### ISSUE TITLE
Incorrect QueueUrl used: preserve docker host in queueUrl

### ISSUE THREAD

**Issue by ShaunParsons** [CoorpAcademy/serverless-plugins#115]
I am running `serverless offline` inside a docker container, and I have my SQS endpoint as `http://elasticmq:9324`. This works fine for creating new queues, but when we fetch the QueueUrl from SQS here: https://github.com/CoorpAcademy/serverless-plugins/blob/18698ebcb77b9de72a122489066b7e0670abea33/packages/serverless-offline-sqs/src/index.js#L211

We get back a QueueUrl of `http://localhost:9324/queue/queue-name` instead of `http://elasticmq:9324/queue/queue-name`, thus causing the fetching of messages from the queue to fail.

I think this is a bug/feature of the `GetQueueUrl` API endpoint, but could we perhaps avoid using it and compute the QueueUrl ourselves?

**Comment by comtom** [comment]
In my case there's a related bug with these same line. When I run serverless offline (latest version) it will call aws to get the queues url. 
This is the log that I'm seeing:
```
 A W S. Simple Queue Service. Non Existent Queue --------
 
  AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
      at Request.extractError (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/event_listeners.js:307:13)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
 ```


I think what we should do here is to parse the config value `serverless-offline-sqs.endpoint` and append `queues/{QueueName}`.

Am I missing something?

**Comment by robpoyntz** [comment]
I was also having this problem. A patch that seems to work on my dev environment is here: https://github.com/CoorpAcademy/serverless-plugins/pull/149/commits/50ea538f049da2921ac98197ccbf5d9e42808ec8

**Comment by IainVM** [comment]
This still seems to be an issue, is there a workaround, or solution?

**Comment by godu** [comment]
Thank you for this idea. I publish this feature in `serverless-offline-sqs@6.0.0`
