### ISSUE TITLE
SQS don't work on a port other than the default (9324)

### ISSUE THREAD

**Issue by gfpacheco** [CoorpAcademy/serverless-plugins#161]
I happen to be working on multiple microservices that depend on their own SQS queue. But if I change the port of the ElasticMQ instance the server doesn't start up:

```
  Unknown Endpoint ---------------------------------------

  UnknownEndpoint: Inaccessible host: `localhost'. This service may not be available in the `us-west-2' region.
      at Request.ENOTFOUND_ERROR (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/event_listeners.js:507:46)
      at Request.callListeners (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/request.js:688:14)
      at ClientRequest.error (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/event_listeners.js:339:22)
      at ClientRequest.<anonymous> (/Users/guilhermepacheco/Workspace/ae/brainbase/vault-backend/node_modules/aws-sdk/lib/http/node.js:96:19)
      at ClientRequest.emit (events.js:315:20)
      at ClientRequest.EventEmitter.emit (domain.js:486:12)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

If I change the port on my docker compose file and my custom config to be 9324 everything works just fine, any other port breaks the server.

**Comment by IainVM** [comment]
I have the same error with the default port number but also inside a docker container
```

**Comment by esteveslima** [comment]
I have the same issue, is there any solution to make this work with docker?
Using from host machine it's working.

**Comment by wellermiranda** [comment]
To make it works, you must run an ElasticMQ container:
`docker run -p 9324:9324 -p 9325:9325 softwaremill/elasticmq-native`

**Comment by monster-anshu** [comment]
> 9324

Thanks. working with the ElasticMQ fine

**Comment by silouone** [comment]
Thanks for the detailed report @gfpacheco — the `UnknownEndpoint: Inaccessible host` error means the configured `endpoint` isn't reaching ElasticMQ on your custom port, so it's worth double-checking that your `custom.serverless-offline-sqs.endpoint` (e.g. `http://localhost:<your-port>`) matches the port your docker-compose actually exposes, since the plugin only talks to the host/port you give it. If your container maps the port correctly and it still fails, could you share your `serverless.yml` `serverless-offline-sqs` block plus the docker-compose port mapping so we can reproduce? 🙏

**Comment by silouone** [comment]
Following up here to close the loop. This isn't a bug in the plugin — `custom.serverless-offline-sqs.endpoint` is the single source of truth for where the plugin connects, and internally `_rewriteQueueUrl` ([`src/sqs.js`](https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/sqs.js)) copies the host, scheme **and port** from that `endpoint` onto every queue URL it resolves. There's nothing special about `9324`: any port is honored, as long as the port in `endpoint` matches the port your ElasticMQ container actually publishes.

The `UnknownEndpoint: Inaccessible host` you hit on a custom port is a mismatch between the `endpoint` port and the published container port (or, in @iainvm's container case, the app reaching ElasticMQ over the wrong host). We've now documented this explicitly in the README — see the new **"`endpoint` and custom ports"** section, including the exact docker-compose port-mapping gotcha — added in #293.

Thanks @gfpacheco for the detailed report and stack trace, and @iainvm / @esteveslima / @wellermiranda for the extra reproductions and the ElasticMQ run command — they're what made the docs concrete. Closing as documented; please reopen if you hit it with a matching port and host and we'll dig in. 🙏
