### ISSUE TITLE
ResourceNotFoundException: Invalid ShardId in ShardIterator

### ISSUE THREAD

**Issue by mdrijwan** [CoorpAcademy/serverless-plugins#164]
not working with my python project! i get the following error. 

``` Resource Not Found Exception ---------------------------

  ResourceNotFoundException: Invalid ShardId in ShardIterator
      at Request.extractError (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/protocol/json.js:52:27)
      at Request.callListeners (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/Users/rijwan/code/g2g/serverless-offer/node_modules/aws-sdk/lib/event_listeners.js:313:13)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1220:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.4
     Framework Version:         2.4.0 (local)
     Plugin Version:            4.1.0
     SDK Version:               2.3.2
     Components Version:        3.2.1```
any help please?

**Comment by rynvelt** [comment]
Same problem here. This is an excerpt from the serverless.yaml:

`
  serverless-offline-dynamodb-streams:
    apiVersion: '2013-12-02'
    endpoint: http://0.0.0.0:8000
    region: eu-central-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500

functions:
  stream-lambda:
    timeout: 10
    handler: src/index.streamHandler
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn: ${self:custom.tableArn}/stream/test-stream/1970-01-01T00:00:00.000
          batchSize: 10
          startingPosition: LATEST
`

I run the DynamoDB in a container with Docker (amazon/dynamodb-local:1.15.0) with the following command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/storage"] on port 8000.
Recreating the database helps, but I assume that this is not expected behavior?

Having a look at https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-dynamodb-streams/src/dynamodb-streams.js and at first glance the plugin is not doing much related to shards.
Searching for the error message "Invalid ShardId in ShardIterator" doesn't lead to anything helpful. Any ideas where to start?

**Comment by silouone** [comment]
Thanks for the report @mdrijwan! The `Invalid ShardId in ShardIterator` error is exactly the kind of shard-iterator/retry handling that was reworked in #265 (on master now, released shortly) — would you mind re-testing your stream setup against master / the next release of `serverless-offline-dynamodb-streams` and letting us know if it resolves? 🙏
