### ISSUE TITLE
serverless-offline-ssm-provider: add default Parameter.Type to resolved offline SSM parameters

### ISSUE THREAD

**Issue by Phebonacci** [CoorpAcademy/serverless-plugins#186]
serverless@2.44.0 
serverless-offline@7.0.0 
serverless-offline-ssm-provider@2.1.0

serverless.yml
```
...
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    API_PREFIX: ${ssm:/editor/api-prefix}
    ...
    
plugins:
  - serverless-offline-ssm-provider
  - serverless-webpack
  - serverless-offline
```

.ssm file
```
/editor/api-prefix=/api/v1
```

When running serverless offline with the configuration above, I would get the following error from serverless:
```
Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.environment.API_PREFIX": Error: Unexpected parameter type: "undefined"
      at Object.resolve (/Users/iona/Work/editor-api/node_modules/serverless/lib/configuration/variables/sources/instance-dependent/get-ssm.js:131:17)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async VariablesResolver.Object.defineProperties.memoizeMethods.resolveSource.d.normalizer.type.type (/Users/iona/Work/editor-api/node_modules/serverless/lib/configuration/variables/resolve.js:472:24),
```

I tried investigating by adding console.logs into `node_modules/serverless-offline-ssm-provider/src/index.js` and can see that the offline variables declared in my `.ssm` file are indeed being read...
```
// console.logs
CONFIG { file: '.ssm' }
VALUES [Function (anonymous)]
NAME /editor/api-prefix
VALUE /api/v1
```
and returned as...
```
{
     Parameter: {
        Value: "/api/v1",
     }
}
```

The problem is, on serverless version 2.44.0, there now is a Parameter.Type checker that throws the error described above when it is not one of `String` | `StringList` | `SecureString`. Please see changes here: https://github.com/serverless/serverless/commit/3f7f67ccc155d61ca9e7aa96c858058da55c635a
file: lib/configuration/variables/sources/instance-dependent/get-ssm.js
line: 109

Would it be possible to set the `Parameter.Type` to `String`? Although this won't work for `StringList`. 
Or maybe we can append a suffix that describes the parameter's type,
or derive the type from the value via regex?

**Comment by silouone** [comment]
Great diagnosis @Phebonacci — you're right that Serverless 2.44+ added a `Parameter.Type` check and the provider currently returns the parameter without one, hence `Unexpected parameter type: "undefined"`. This wasn't part of the recent #265 work, so it's still a real open bug; defaulting `Type` to `String` (and ideally inferring `StringList`/`SecureString` where detectable) sounds like the right fix, and a PR from you would be very welcome. 🙏
