### ISSUE TITLE
serverless-offline-sqs breaks when upgrading @aws-sdk from 3.226.0 to 3.556.0

### ISSUE THREAD

**Issue by serg06** [CoorpAcademy/serverless-plugins#260]
Library version:

```
serverless-offline-sqs": "^7.3.2"
```

Breaking code:
```
  await sqs.send(
    new SendMessageCommand({
      MessageBody: JSON.stringify(data),
      QueueUrl: Config.TASKS_QUEUE_URL,
    })
  );
```

Stack trace:
```
SyntaxError: Unexpected token < in JSON at position 0\n  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at JSON.parse (<anonymous>)
    at C:\\repo\\mono\\node_modules\\@aws-sdk\\core\\dist-cjs\\index.js:323:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at parseJsonErrorBody (C:\\repo\\mono\\node_modules\\@aws-sdk\\core\\dist-cjs\\index.js:336:17)
    at de_CommandError (C:\\repo\\mono\\node_modules\\@aws-sdk\\client-sqs\\dist-cjs\\index.js:1191:11)
    at C:\\repo\\mono\\node_modules\\@smithy\\middleware-serde\\dist-cjs\\index.js:35:20
    at C:\\repo\\mono\\node_modules\\@smithy\\core\\dist-cjs\\index.js:165:18
    at C:\\repo\\mono\\node_modules\\@smithy\\middleware-retry\\dist-cjs\\index.js:320:38
    at C:\\repo\\mono\\node_modules\\@aws-sdk\\middleware-sdk-sqs\\dist-cjs\\index.js:130:16
    at C:\\repo\\mono\\node_modules\\@aws-sdk\\middleware-logger\\dist-cjs\\index.js:33:22
    at {the code I linked above}
```

What it's trying to parse:

```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

How I tried fixing it:
- Upgrading to serverless-offline-sqs 8.0.0. The error above just turned into an "UnknownError" instead.

**Comment by serg06** [comment]
Do I need to update my `localstack` which is running sqs? It's running a pretty old version

**Comment by tanguybernard** [comment]
Hello, I have almost same issue with different dependencies

```
SyntaxError: Unexpected token 'T', "There was "... is not valid JSON
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at JSON.parse (<anonymous>)
```

My dependencies:


```
"serverless": "^3.38.0",
"serverless-offline": "^13.6.0",
"serverless-offline-sqs": "^8.0.0",
"serverless-plugin-typescript": "^2.1.5",
"ts-node": "^10.9.2",
"tsx": "^4.11.2",
"typescript": "^5.4.5"

"@aws-sdk/client-lambda": "^3.504.0",
"@aws-sdk/client-sqs": "^3.226.0",
"@aws-sdk/lib-dynamodb": "^3.587.0",
"aws-sdk": "^2.1634.0"
```

Its working with __aws-sdk (v2)__ but not with __@aws-sdk/client-sqs (v3)__

If someone has a clue ?? I can help myself but I don't know where to look !

**Comment by terozio** [comment]
@aws-sdk/client-sqs has changed to use JSON as the communication protocol and expects to receive it since version [v3.447.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.447.0) More information here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-json-faqs.html#json-protocol-getting-started
 
Those errors sound like JSON parsing encounters xml content and fails because of that. Maybe its elastic mq which should be updated accordingly? Anyways I'm stuck with the same issue currently.

**Comment by terozio** [comment]
Turns out elasticmq was the issue. After bumping to a more recent version it started working out of the box for me.

**Comment by rod-stuchi** [comment]
> Turns out elasticmq was the issue. After bumping to a more recent version it started working out of the box for me.

I was getting this error:
```
  body: '<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">\n' +
    '      <Error>\n' +
    '        <Type>Sender</Type>\n' +
    '        <Code>MissingAction</Code>\n' +
    '        <Message>MissingAction; see the SQS docs.</Message>\n' +
    '        <Detail/>\n' +
    '      </Error>\n' +
    '      <RequestId>00000000-0000-0000-0000-000000000000</RequestId>\n' +
    '    </ErrorResponse>'

```


it never crossed my mind that the problem could be `elasticmq-server-1.3.3.jar` and it was, updating to `elasticmq-server-all-1.6.8.jar` solved the problem.

@terozio thank you for posting it

**Comment by silouone** [comment]
Root cause is an **outdated ElasticMQ/LocalStack** speaking the legacy XML/Query protocol while `@aws-sdk/client-sqs` ≥3.447.0 switched to JSON — which is exactly why upgrading ElasticMQ (1.3.3 → 1.6.8) fixed it in-thread (thanks @terozio, @rod-stuchi). It isn't a defect in `serverless-offline-sqs`. We are separately migrating the plugin's own SDK to v3 (repo-wide) to clear the maintenance-mode warning, but for the JSON-parse error the fix is **bumping ElasticMQ**. Closing as resolved — reopen if a current ElasticMQ still reproduces it. 🙏
