### ISSUE TITLE
SQS Offline event handler error

### ISSUE THREAD

**Issue by jaffacake** [CoorpAcademy/serverless-plugins#57]
Hi,

When running an SQS event handler, I was getting the following error:

```
Serverless: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at getConfig (/Users/grantfellows/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:30:17)
    at ServerlessOfflineSQS.eventHandler (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:96:30)
    at cb (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:194:41)
    at Promise (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:21:5)
    at new Promise (<anonymous>)
    at fromCallback (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:20:3)
    at next (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:194:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I traced it down to this line:
```
    const {location = '.'} = getConfig(this.service, this.options, 'serverless-offline');
```

This causes errors if you don't have any custom serverless-offline variables defined in your yaml.

I had to fix this by adding in the following to my yaml:

```
custom:
  serverless-offline:
    test: test
```

I think the configuration lookup needs to be more graceful to handle this scenario.

**Comment by jaffacake** [comment]
PR opened: https://github.com/CoorpAcademy/serverless-plugins/pull/58

**Comment by dennermiranda** [comment]
I am having the same issue. The more interesting is that `[..] = getConfig(this.service, this.options, 'serverless-offline');` is called twice, thus, in fact, you should be able to do just:
`const {location = '.'} = this.config`.

I also noticed that I am getting different configurations on the constructor and on the eventHandler calls:


```
Constructor call:

custom:
   { 'serverless-offline-sqs':
      { autoCreate: false,
        apiVersion: '2012-11-05',
        endpoint:
         'https://sqs.us-east-2.amazonaws.com/billing',
        region: 'us-east-2',
        accessKeyId: 'root',
        secretAccessKey: 'root',
        skipCacheInvalidation: false } }

Event handler call:

custom:
   { 'serverless-offline-sqs':
      { autoCreate: false,
        apiVersion: '2012-11-05',
        endpoint:
         'https://sqs.us-east-2.amazonaws.com/billing',
        region: 'us-east-2',
        accessKeyId: 'root',
        secretAccessKey: 'root',
        skipCacheInvalidation: true } }

As you can see the last option was reversed.

**Comment by godu** [comment]
Take a look to https://github.com/CoorpAcademy/serverless-plugins/pull/61 :)
