### ISSUE TITLE
Applying serverless-apigateway-access-logs to existing Stack

### ISSUE THREAD

**Issue by noanflaherty** [CoorpAcademy/serverless-plugins#64]
I have a serverless lambda stack that has been in place for some time. Recently, we began wanting to write API Gateway Access Logs for our existing API Gateway API. This plugin appears to do _exactly_ what we want, except it seems to have issues when trying to add it to a pre-existing API Gateway API.

When I run `sls deploy` I get the following error:

```
CloudFormation - CREATE_FAILED - AWS::ApiGateway::Stage - ApiGatewayStage

18:54:20 Serverless: Operation failed!
18:54:20  
18:54:20   Serverless Error ---------------------------------------
18:54:20  
18:54:20   An error occurred: ApiGatewayStage - staging already exists.
18:54:20  
18:54:20   Stack Trace --------------------------------------------
18:54:20  
18:54:20 ServerlessError: An error occurred: ApiGatewayStage - staging already exists.
18:54:20     at provider.request.then (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
18:54:20 From previous event:
18:54:20     at AwsDeploy.monitorStack (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
18:54:20     at provider.request.then (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:30)
18:54:20 From previous event:
18:54:20     at AwsDeploy.update (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
18:54:20 From previous event:
18:54:20     at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:112:12)
18:54:20 From previous event:
18:54:20     at AwsDeploy.updateStack (/usr/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:106:8)
18:54:20 From previous event:
18:54:20     at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:129:39)
18:54:20 From previous event:
18:54:20     at Object.aws:deploy:deploy:updateStack [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:125:10)
18:54:20     at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
18:54:20 From previous event:
18:54:20     at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
18:54:20     at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
18:54:20     at AwsDeploy.BbPromise.bind.then (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
18:54:20 From previous event:
18:54:20     at Object.deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
18:54:20     at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
18:54:20 From previous event:
18:54:20     at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
18:54:20     at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
18:54:20     at variables.populateService.then.then (/usr/lib/node_modules/serverless/lib/Serverless.js:157:33)
18:54:20     at runCallback (timers.js:705:18)
18:54:20     at tryOnImmediate (timers.js:676:5)
18:54:20     at processImmediate (timers.js:658:5)
18:54:20     at process.topLevelDomainCallback (domain.js:120:23)
18:54:20 From previous event:
18:54:20     at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:144:8)
18:54:20     at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:43:50)
```

Is there any way to add this plugin to my serverless config and deploy successfully without having to delete my entire Cloud Formation stack?

**Comment by nitan84** [comment]
👍 - Would like to have this work with an existing stack as well

**Comment by AdrieanKhisbe** [comment]
@noanflaherty Sorry for the late answer.
Unfortunately I did not find a way back then (when the plugin was created) to add plugin without recreating the stack.

This is because the ApiGateWay stage is overidded. (hence the conflict when updating the stack)
cf
https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-apigateway-access-logs/src/index.js#L45

the stage is created magicly by ApiGatewayDeployment by default in serverless. Stage does not exist as ressource in cloudformation (either template or stack),  we cannot then add Configuration to it.

(If I remember well, There was a discussion in the serverless repository, about having a default Stage. However I admit I lost track)

**Comment by silouone** [comment]
Thanks for the detailed write-up @noanflaherty — the "ApiGatewayStage already exists" failure on a pre-existing API/stage is a separate concern from the #265 work, so we're keeping this open as a feature request; in the meantime the usual workaround is to let the plugin own/manage the stage resource so CloudFormation isn't asked to re-create an existing one. 🙏
