### ISSUE TITLE
[serverless-offline-sqs] Doesn't work with the latest serverless-offline 

### ISSUE THREAD

**Issue by vkartaviy** [CoorpAcademy/serverless-plugins#72]
```
"serverless": "^1.46.1",
"serverless-offline": "^5.7.2",
"serverless-offline-sqs": "^2.0.3",
```

```  
Error --------------------------------------------------

  Cannot find module 'serverless-offline/src/createLambdaContext'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module 'serverless-offline/src/createLambdaContext'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/node_modules/serverless-offline-sqs/src/index.js:18:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at plugins.forEach (~/node_modules/serverless/lib/classes/PluginManager.js:105:24)
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (~/node_modules/serverless/lib/classes/PluginManager.js:101:13)
    at PluginManager.loadServicePlugins (~/node_modules/serverless/lib/classes/PluginManager.js:156:10)
    at PluginManager.loadAllPlugins (~/node_modules/serverless/lib/classes/PluginManager.js:96:10)
    at pluginManager.loadConfigFile.then.then (~/node_modules/serverless/lib/Serverless.js:74:26)
From previous event:
    at Serverless.init (~/node_modules/serverless/lib/Serverless.js:72:8)
    at initializeErrorReporter.then (~/node_modules/serverless/bin/serverless:42:21)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ~/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (~/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.12.0
     Serverless Version:     1.46.1
```

**Comment by tomzaku** [comment]
+1

**Comment by NathanWenslaff** [comment]
We are having the same issue

**Comment by paypr** [comment]
This is still failing with `serverless-offline` version `6.1.4`.

**Comment by mdnorman** [comment]
This is still failing with `serverless-offline` version `6.1.4`.

**Comment by CodeNinja1395** [comment]
Hey! i`m facing similar problem
`Error: Cannot find module 'serverless-offline/src/functionHelper'`
if I delete serverless-offline-sqs, everything works fine.
