### ISSUE TITLE
YAMLException: duplicated mapping key

### ISSUE THREAD

**Issue by thetumper** [CoorpAcademy/serverless-plugins#80]
After adding serverless-offline-sqs plugin and configuration, startup fails with the following output:

myservice    |   YAMLException: duplicated mapping key in "/var/task/serverless.yml" at line 2, column 1:
myservice    |       Serverless: Load command config: ... 
myservice    |       ^
myservice    |       at generateError (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
myservice    |       at throwError (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
myservice    |       at storeMappingPair (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
myservice    |       at readBlockMapping (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
myservice    |       at composeNode (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
myservice    |       at readDocument (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
myservice    |       at loadDocuments (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
myservice    |       at Object.load (/var/task/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
myservice    |       at loadYaml (/var/task/node_modules/serverless/lib/utils/fs/parse.js:12:17)
myservice    |       at parse (/var/task/node_modules/serverless/lib/utils/fs/parse.js:30:16)
myservice    |       at fse.readFileAsync.then.contents (/var/task/node_modules/serverless/lib/utils/fs/readFile.js:7:63)
myservice    |       at /var/task/node_modules/graceful-fs/graceful-fs.js:90:16
myservice    |       at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
myservice    |   From previous event:
myservice    |       at readFile (/var/task/node_modules/serverless/lib/utils/fs/readFile.js:7:46)
myservice    |       at getServerlessConfigFilePath.then.configFilePath (/var/task/node_modules/serverless/lib/utils/getServerlessConfigFile.js:73:16)
myservice    |   From previous event:
myservice    |       at Object._.memoize.serverless (/var/task/node_modules/serverless/lib/utils/getServerlessConfigFile.js:65:45)
myservice    |       at Object.memoized [as getServerlessConfigFile] (/var/task/node_modules/lodash/lodash.js:10552:27)
myservice    |       at PluginManager.loadConfigFile (/var/task/node_modules/serverless/lib/classes/PluginManager.js:48:8)
myservice    |       at Serverless.init (/var/task/node_modules/serverless/lib/Serverless.js:65:8)
myservice    |       at initializeErrorReporter.then (/var/task/node_modules/serverless/bin/serverless.js:59:6)
myservice    |       at runCallback (timers.js:794:20)
myservice    |       at tryOnImmediate (timers.js:752:5)
myservice    |       at processImmediate [as _immediateCallback] (timers.js:729:5)
myservice    |   From previous event:
myservice    |       at Object.<anonymous> (/var/task/node_modules/serverless/bin/serverless.js:46:39)
myservice    |       at Module._compile (module.js:652:30)
myservice    |       at Object.Module._extensions..js (module.js:663:10)
myservice    |       at Module.load (module.js:565:32)
myservice    |       at tryModuleLoad (module.js:505:12)
myservice    |       at Function.Module._load (module.js:497:3)
myservice    |       at Function.Module.runMain (module.js:693:10)
myservice    |       at startup (bootstrap_node.js:188:16)
myservice    |       at bootstrap_node.js:609:3
myservice    |  
myservice    |   Get Support --------------------------------------------
myservice    |      Docs:          docs.serverless.com
myservice    |      Bugs:          github.com/serverless/serverless/issues
myservice    |      Issues:        forum.serverless.com
myservice    |  
myservice    |   Your Environment Information ---------------------------
myservice    |      Operating System:          linux
myservice    |      Node Version:              8.10.0
myservice    |      Framework Version:         1.51.0
myservice    |      Plugin Version:            1.3.9
myservice    |      SDK Version:               2.1.0

YAML actually does not contain any duplicate keys.  Verified with sls print, and by using cfn-flip to convert to JSON.

Configuration looks like this:

# Plugin Configurations
# ----------------------
plugins:
  - serverless-plugin-aws-alerts
  - serverless-plugin-tracing
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline-sqs
  - serverless-offline # Must be loaded last

# Custom Configurations
# ----------------------
custom:
  # Configurations for serverless-plugin-aws-alerts
  alerts: ${file(serverless/lambda-cloudwatch-alerts.yml)}

  # Configurations for serverless-webpack
  webpack:
    # enable auto-packing of external modules since webpack
    # uses webpack-node-externals
    includeModules: true

  # Configuration for serverless-offline-sqs
  serverless-offline-sqs:
    autoCreate: false
    apiVersion: '2012-11-05' # AWS SQS API version
    endpoint: http://localhost:4576
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

**Comment by thetumper** [comment]
Update:  after removing SLS_DEBUG, this issue went away, and it's now failing with the error mentioned in #21 :  "AWS.SimpleQueueService.NonExistentQueue: AWS.SimpleQueueService.NonExistentQueue; see the SQS docs."

Closing this.
